(()=>{"use strict";
const DATA_KEY="teamboard-v5-data",MASTER_KEY="teamboard-v5-masters",MATCH_KEY="teamboard-v9-matches",MATERIAL_KEY="teamboard-v21-materials",SYNC_KEY="teamboard-v5-sync";
const $=id=>document.getElementById(id), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>new Date().toISOString().slice(0,10);
const defaultMasters={categories:["攻撃","守備","切替","ポゼッション","フィニッシュ"],ages:["U-8","U-10","U-12","U-15","U-18","TOP"],times:["30分","45分","60分","90分"],tags:["攻撃","守備","前進","サポート","少人数","ゲーム"],players:[],surfaceType:"soccer"};
let sessions=load(DATA_KEY,[]),masters={...defaultMasters,...load(MASTER_KEY,{})},matches=load(MATCH_KEY,[]),materials=load(MATERIAL_KEY,[]);
let draft=null,activePart="wup",activeTool="attack",selectedObjectId="",interaction=null,currentRotation=0,pendingMaterialFile=null,memberState={},substitutions=[];
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1600)}
function ensureData(){if(!Array.isArray(sessions))sessions=[];if(!Array.isArray(matches))matches=[];if(!Array.isArray(materials))materials=[];if(!Array.isArray(masters.players))masters.players=[];if(!sessions.length){sessions=[sampleSession()];saveAll()}saveMasters()}
function saveAll(){save(DATA_KEY,sessions)}function saveMasters(){save(MASTER_KEY,masters)}function saveMatches(){save(MATCH_KEY,matches)}function saveMaterials(){save(MATERIAL_KEY,materials)}
function page(id){qsa(".page").forEach(p=>p.classList.toggle("active",p.id===id));qsa(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===id));scrollTo({top:0,behavior:"smooth"})}
function refreshSelects(){const opt=a=>a.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");$("age").innerHTML=opt(masters.ages);$("category").innerHTML=opt(masters.categories);$("timePlan").innerHTML=opt(masters.times);$("categoryFilter").innerHTML='<option value="">全分類</option>'+opt(masters.categories);$("matchCategory").innerHTML=opt(masters.ages);$("materialCategory").innerHTML=opt(masters.ages);$("surfaceType").value=masters.surfaceType||"soccer";$("masterCategories").value=masters.categories.join("\n");$("masterAges").value=masters.ages.join("\n");$("masterTimes").value=masters.times.join("\n");$("masterTags").value=masters.tags.join("\n")}
function emptyParts(){const parts={};["wup","tr1","tr2","game"].forEach(k=>parts[k]={purpose:"",org:"",coaching:"",evaluation:"",objects:[]});return parts}
function newEmptySession(){return{id:uid(),title:"",age:masters.ages[0]||"U-12",category:masters.categories[0]||"攻撃",timePlan:masters.times[2]||"60分",tags:"",parts:emptyParts(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function sampleSession(){const s=newEmptySession();s.title="サンプル：前進するサポート";s.tags="攻撃,前進";s.parts.wup.objects=[{id:uid(),type:"attack",x:260,y:260,s:1,r:0,color:"#e62922"},{id:uid(),type:"defense",x:420,y:260,s:1,r:0,color:"#1669df"},{id:uid(),type:"free",x:340,y:360,s:1,r:0,color:"#219529"},{id:uid(),type:"ball",x:520,y:340,s:1,r:0,color:"#fff"},{id:uid(),type:"arrow",x1:275,y1:260,x2:500,y2:335,color:"#fff"}];return s}
function normalizeSession(s){if(!s.parts)s.parts=emptyParts();["wup","tr1","tr2","game"].forEach(k=>{if(!s.parts[k])s.parts[k]={purpose:"",org:"",coaching:"",evaluation:"",objects:[]};if(!Array.isArray(s.parts[k].objects))s.parts[k].objects=[]});return s}
function newSession(){draft=newEmptySession();fillSessionForm();setPart("wup");page("createPage")}
function loadDraft(s){draft=normalizeSession(clone(s));fillSessionForm();setPart("wup");page("createPage")}
function fillSessionForm(){$("sessionId").value=draft.id;$("title").value=draft.title||"";$("age").value=draft.age||masters.ages[0]||"";$("category").value=draft.category||masters.categories[0]||"";$("timePlan").value=draft.timePlan||masters.times[0]||"";$("tags").value=draft.tags||"";fillPartText()}
function readSessionForm(){draft.title=$("title").value.trim()||"無題の指導案";draft.age=$("age").value;draft.category=$("category").value;draft.timePlan=$("timePlan").value;draft.tags=$("tags").value.trim()}
function fillPartText(){const p=draft.parts[activePart];$("purpose").value=p.purpose||"";$("org").value=p.org||"";$("coaching").value=p.coaching||"";$("evaluation").value=p.evaluation||""}
function readPartText(){if(!draft)return;const p=draft.parts[activePart];p.purpose=$("purpose").value;p.org=$("org").value;p.coaching=$("coaching").value;p.evaluation=$("evaluation").value}
function setPart(p){if(draft)readPartText();activePart=p;qsa(".part").forEach(b=>b.classList.toggle("active",b.dataset.part===p));$("partName").textContent={wup:"W-up",tr1:"TR1",tr2:"TR2",game:"Game"}[p];if(draft)fillPartText();selectedObjectId="";renderBoard()}
function saveDraft(){readPartText();readSessionForm();draft.updatedAt=new Date().toISOString();const i=sessions.findIndex(s=>s.id===draft.id);if(i>=0)sessions[i]=clone(draft);else sessions.unshift(clone(draft));saveAll();renderAll();toast("保存しました")}
function filteredSessions(){const kw=$("keyword").value.toLowerCase(),pf=$("partFilter").value,cf=$("categoryFilter").value,tf=$("tagFilter").value;return sessions.map(normalizeSession).filter(s=>{const hay=[s.title,s.age,s.category,s.timePlan,s.tags,...Object.values(s.parts).flatMap(p=>[p.purpose,p.org,p.coaching,p.evaluation])].join(" ").toLowerCase();if(kw&&!hay.includes(kw))return false;if(cf&&s.category!==cf)return false;if(tf&&!String(s.tags||"").includes(tf))return false;if(pf){const p=s.parts[pf];if(![p.purpose,p.org,p.coaching,p.evaluation,JSON.stringify(p.objects)].join(" ").toLowerCase().includes(kw))return false}return true})}
function cardHtml(s){return`<article class="card" data-id="${s.id}"><h3>${esc(s.title)}</h3><div class="badges"><span class="badge">${esc(s.age)}</span><span class="badge">${esc(s.category)}</span><span class="badge">${esc(s.timePlan)}</span></div><p>${esc(s.tags||"")}</p><div class="card-actions"><button data-act="edit">編集</button><button data-act="copy">コピー</button><button data-act="delete" class="danger">削除</button></div></article>`}
function bindCards(root){qsa("[data-act]",root).forEach(b=>b.onclick=()=>{const id=b.closest(".card").dataset.id,act=b.dataset.act,s=sessions.find(x=>x.id===id);if(act==="edit")loadDraft(s);if(act==="copy"){const c=clone(s);c.id=uid();c.title=(c.title||"無題")+" コピー";sessions.unshift(c);saveAll();renderAll()}if(act==="delete"&&confirm("削除しますか？")){sessions=sessions.filter(x=>x.id!==id);saveAll();renderAll()}})}
function renderRecent(){const list=$("recentList");list.innerHTML=sessions.slice(0,5).map(cardHtml).join("")||empty("指導案がありません","新規作成してください");bindCards(list)}
function renderSearch(){const list=$("resultList");list.innerHTML=filteredSessions().map(cardHtml).join("")||empty("該当なし","条件を変えてください");bindCards(list);renderTags()}
function renderTags(){const tags=[...new Set(sessions.flatMap(s=>String(s.tags||"").split(/[,\s、]+/).filter(Boolean)).concat(masters.tags||[]))];$("tagFilter").innerHTML='<option value="">全タグ</option>'+tags.map(t=>`<option>${esc(t)}</option>`).join("")}
function empty(h,p){return`<div class="card"><h3>${h}</h3><p>${p}</p></div>`}

function svgPoint(e){const svg=$("board"),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const r=pt.matrixTransform(svg.getScreenCTM().inverse());return{x:r.x,y:r.y}}
function currentObjects(){return draft.parts[activePart].objects}
function getSelected(){return currentObjects().find(o=>o.id===selectedObjectId)}
function objectColor(){return $("partColor").value||"#fff"}
function setTool(t){activeTool=t;interaction=null;qsa(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));$("toolName").textContent={attack:"攻撃",defense:"守備",free:"フリーマン",ball:"ボール",cone:"コーン",marker:"マーカー",goalFrame:"ゴール枠",courtArea:"ペナルティエリア",centerLine:"センターライン",centerCircle:"センターサークル",shapeCircle:"円",horizontalLine:"横線",verticalLine:"縦線",text:"テキスト",line:"白線",arrow:"矢印",dash:"点線矢印"}[t]||t;const d={attack:"#e62922",defense:"#1669df",free:"#219529",cone:"#ff7a00",marker:"#ffcc00",line:"#ffffff",arrow:"#ffffff",dash:"#ffffff",courtArea:"#ffffff",goalFrame:"#ffffff",centerLine:"#ffffff",centerCircle:"#ffffff",shapeCircle:"#ffffff",horizontalLine:"#ffffff",verticalLine:"#ffffff",text:"#ffffff",ball:"#ffffff"};$("partColor").value=d[t]||"#fff"}
function playerShape(x,y,color,s=1){return`<g><circle cx="${x}" cy="${y}" r="${26*s}" fill="${color}" stroke="#fff" stroke-width="${4*s}"/><circle cx="${x}" cy="${y-4*s}" r="${9*s}" fill="#fff"/><path d="M ${x-14*s} ${y+11*s} Q ${x} ${y+31*s} ${x+14*s} ${y+11*s} Q ${x+17*s} ${y+2*s} ${x+9*s} ${y+2*s} Q ${x} ${y+11*s} ${x-9*s} ${y+2*s} Q ${x-17*s} ${y+2*s} ${x-14*s} ${y+11*s} Z" fill="#fff"/><rect x="${x-34*s}" y="${y+8*s}" width="${23*s}" height="${9*s}" rx="${4*s}" fill="#fff" transform="rotate(-32 ${x-22*s} ${y+12*s})"/><rect x="${x+11*s}" y="${y+8*s}" width="${23*s}" height="${9*s}" rx="${4*s}" fill="#fff" transform="rotate(32 ${x+22*s} ${y+12*s})"/><path d="M ${x} ${y-39*s} L ${x-8*s} ${y-27*s} Q ${x} ${y-31*s} ${x+8*s} ${y-27*s} Z" fill="#fff"/></g>`}
function ballShape(x,y,s=1){const p=[[0,-9],[8,-3],[5,7],[-5,7],[-8,-3]].map(a=>`${x+a[0]*s},${y+a[1]*s}`).join(" ");return`<g><circle cx="${x}" cy="${y}" r="${17*s}" fill="#fff" stroke="#111" stroke-width="${3*s}"/><polygon points="${p}" fill="#111"/></g>`}
function shapeSvg(o){const s=o.s||1,c=o.color||"#fff";if(o.type==="attack")return playerShape(o.x,o.y,o.color||"#e62922",s);if(o.type==="defense")return playerShape(o.x,o.y,o.color||"#1669df",s);if(o.type==="free")return playerShape(o.x,o.y,o.color||"#219529",s);if(o.type==="ball")return ballShape(o.x,o.y,s);if(o.type==="cone")return`<g><path d="M ${o.x} ${o.y-24*s} L ${o.x+22*s} ${o.y+24*s} L ${o.x-22*s} ${o.y+24*s} Z" fill="${c||"#ff7a00"}"/><ellipse cx="${o.x}" cy="${o.y+24*s}" rx="${26*s}" ry="${8*s}" fill="${c||"#ff7a00"}"/></g>`;if(o.type==="marker")return`<circle cx="${o.x}" cy="${o.y}" r="${22*s}" fill="${c||"#ffcc00"}" stroke="#fff" stroke-width="${3*s}"/>`;if(o.type==="goalFrame")return`<g transform="rotate(${o.r||0} ${o.x} ${o.y})"><path d="M ${o.x-55*s} ${o.y+28*s} L ${o.x-55*s} ${o.y-28*s} L ${o.x+55*s} ${o.y-28*s} L ${o.x+55*s} ${o.y+28*s}" fill="none" stroke="${c}" stroke-width="${7*s}" stroke-linecap="round"/></g>`;if(o.type==="courtArea")return`<g transform="rotate(${o.r||0} ${o.x} ${o.y})"><rect x="${o.x-135*s}" y="${o.y-128*s}" width="${270*s}" height="${184*s}" fill="none" stroke="${c}" stroke-width="${8*s}"/><path d="M ${o.x-59*s} ${o.y-128*s} L ${o.x-59*s} ${o.y-68*s} L ${o.x+59*s} ${o.y-68*s} L ${o.x+59*s} ${o.y-128*s}" fill="none" stroke="${c}" stroke-width="${6*s}"/><circle cx="${o.x}" cy="${o.y-23*s}" r="${6*s}" fill="${c}"/><path d="M ${o.x-62*s} ${o.y+56*s} A ${74*s} ${74*s} 0 0 0 ${o.x+62*s} ${o.y+56*s}" fill="none" stroke="${c}" stroke-width="${6*s}"/></g>`;if(o.type==="centerLine")return`<line x1="${o.x-150*s}" y1="${o.y}" x2="${o.x+150*s}" y2="${o.y}" stroke="${c}" stroke-width="${7*s}" stroke-linecap="round"/>`;if(o.type==="centerCircle"||o.type==="shapeCircle")return`<circle cx="${o.x}" cy="${o.y}" r="${o.type==="centerCircle"?70*s:52*s}" fill="none" stroke="${c}" stroke-width="${8*s}"/>`;if(o.type==="horizontalLine")return`<g transform="rotate(${o.r||0} ${o.x} ${o.y})"><line x1="${o.x-75*s}" y1="${o.y}" x2="${o.x+75*s}" y2="${o.y}" stroke="${c}" stroke-width="${9*s}" stroke-linecap="round"/></g>`;if(o.type==="verticalLine")return`<g transform="rotate(${o.r||0} ${o.x} ${o.y})"><line x1="${o.x}" y1="${o.y-75*s}" x2="${o.x}" y2="${o.y+75*s}" stroke="${c}" stroke-width="${9*s}" stroke-linecap="round"/></g>`;if(o.type==="text")return`<text x="${o.x}" y="${o.y}" fill="${c}" font-size="${24*s}" font-weight="800" text-anchor="middle">${esc(o.text||"テキスト")}</text>`;return""}
function lineSvg(o){const c=o.color||"#fff",dash=o.type==="dash"?'stroke-dasharray="12 10"':"",head=o.type==="arrow"||o.type==="dash"?`<polygon points="${o.x2},${o.y2} ${o.x2-14},${o.y2-7} ${o.x2-14},${o.y2+7}" fill="${c}" transform="rotate(${Math.atan2(o.y2-o.y1,o.x2-o.x1)*180/Math.PI} ${o.x2} ${o.y2})"/>`:"";return`<line x1="${o.x1}" y1="${o.y1}" x2="${o.x2}" y2="${o.y2}" stroke="${c}" stroke-width="6" stroke-linecap="round" ${dash}/>${head}`}
function bounds(o){if(o.x1!==undefined){const x=Math.min(o.x1,o.x2),y=Math.min(o.y1,o.y2),w=Math.abs(o.x2-o.x1),h=Math.abs(o.y2-o.y1);return{x,y,w,h}}const s=o.s||1,map={attack:[64,64],defense:[64,64],free:[64,64],ball:[44,44],cone:[60,70],marker:[52,52],goalFrame:[130,80],courtArea:[300,220],centerLine:[320,40],centerCircle:[160,160],shapeCircle:[130,130],horizontalLine:[170,40],verticalLine:[40,170],text:[120,40]};const [w,h]=map[o.type]||[80,80];return{x:o.x-w*s/2,y:o.y-h*s/2,w:w*s,h:h*s}}
function renderBoard(){if(!draft)return;const objs=currentObjects();let html="";for(let i=0;i<1000;i+=100)html+=`<rect class="grass-stripe" x="${i}" y="0" width="50" height="640"/>`;html+=objs.map(o=>`<g data-id="${o.id}">${o.x1!==undefined?lineSvg(o):shapeSvg(o)}</g>`).join("");const sel=getSelected();if(sel){const b=bounds(sel);html+=`<rect class="selected-outline" x="${b.x-6}" y="${b.y-6}" width="${b.w+12}" height="${b.h+12}" rx="10"/>`}$("board").innerHTML=html;updateSelectedInfo()}
function currentObjects(){return draft.parts[activePart].objects}function getSelected(){return currentObjects().find(o=>o.id===selectedObjectId)}
function createObj(p){if(["line","arrow","dash"].includes(activeTool)){interaction={mode:"draw",obj:{id:uid(),type:activeTool,x1:p.x,y1:p.y,x2:p.x,y2:p.y,color:objectColor()}};currentObjects().push(interaction.obj);selectedObjectId=interaction.obj.id;return}let obj;if(activeTool==="text"){obj={id:uid(),type:"text",x:p.x,y:p.y,s:1,r:currentRotation,color:objectColor(),text:prompt("テキスト","テキスト")||"テキスト"}}else obj={id:uid(),type:activeTool,x:p.x,y:p.y,s:1,r:currentRotation,color:objectColor()};currentObjects().push(obj);selectedObjectId=obj.id;renderBoard()}
function boardDown(e){const p=svgPoint(e),target=e.target.closest("[data-id]");if(target){selectedObjectId=target.dataset.id;const o=getSelected();if(o)interaction={mode:"move",id:o.id,start:p,orig:clone(o)};renderBoard();return}createObj(p)}
function boardMove(e){if(!interaction)return;const p=svgPoint(e),o=getSelected();if(!o)return;if(interaction.mode==="draw"){o.x2=p.x;o.y2=p.y}else if(interaction.mode==="move"){const dx=p.x-interaction.start.x,dy=p.y-interaction.start.y;if(o.x1!==undefined){o.x1=interaction.orig.x1+dx;o.y1=interaction.orig.y1+dy;o.x2=interaction.orig.x2+dx;o.y2=interaction.orig.y2+dy}else{o.x=interaction.orig.x+dx;o.y=interaction.orig.y+dy}}renderBoard()}
function boardUp(){interaction=null}function svgPoint(e){const svg=$("board"),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function updateSelectedInfo(){const o=getSelected();$("selectedInfo").textContent=o?`選択中：${o.type}`:"未選択";if(o&&o.color)$("partColor").value=o.color}
function adjustSize(f){const o=getSelected();if(!o||o.x1!==undefined)return;o.s=Math.max(.35,Math.min(3,(o.s||1)*f));renderBoard()}function rotate(d){currentRotation=(currentRotation+d+360)%360;$("rotationValue").textContent=currentRotation+"°";const o=getSelected();if(o&&o.x1===undefined){o.r=((o.r||0)+d+360)%360;renderBoard()}}
function duplicate(){const o=getSelected();if(!o)return;const c=clone(o);c.id=uid();if(c.x1!==undefined){c.x1+=24;c.x2+=24;c.y1+=24;c.y2+=24}else{c.x+=24;c.y+=24}currentObjects().push(c);selectedObjectId=c.id;renderBoard()}function del(){if(!selectedObjectId)return;draft.parts[activePart].objects=currentObjects().filter(o=>o.id!==selectedObjectId);selectedObjectId="";renderBoard()}function applyColor(){const o=getSelected();if(!o){toast("パーツを選択してください");return}o.color=objectColor();renderBoard();toast("色を変更しました")}

function renderMatches(){const list=$("matchList");list.innerHTML=matches.map(m=>`<article class="card" data-mid="${m.id}"><h3>${esc(m.matchName||"試合")}</h3><div class="badges"><span class="badge">${m.matchType==="trm"?"TRM":"公式戦"}</span><span class="badge">${esc(m.opponentName||"-")}</span><span class="badge">${esc(m.totalFor??0)}-${esc(m.totalAgainst??0)}</span></div><p>${esc(m.matchMemo||"")}</p><div class="card-actions"><button data-match-edit="${m.id}">編集</button><button class="danger" data-match-del="${m.id}">削除</button></div></article>`).join("")||empty("試合結果がありません","入力して保存してください");qsa("[data-match-edit]").forEach(b=>b.onclick=()=>editMatch(b.dataset.matchEdit));qsa("[data-match-del]").forEach(b=>b.onclick=()=>{if(confirm("削除しますか？")){matches=matches.filter(m=>m.id!==b.dataset.matchDel);saveMatches();renderMatches()}})}
function clearMatch(){["matchId","matchName","opponentName","videoUrl","matchMemo"].forEach(id=>$(id).value="");$("matchDate").value=today();$("matchType").value="official";$("trmCount").value="3";$("formationInput").value="4-4-2";memberState={};substitutions=[];renderScoreInputs();renderMemberEditor()}
function renderScoreInputs(){const trm=$("matchType").value==="trm";$("trmCount").disabled=!trm;if(trm){const n=Number($("trmCount").value||3);$("scoreInputs").innerHTML=Array.from({length:n},(_,i)=>`<label>${i+1}本目 得点<input type="number" class="score-for" value="0"></label><label>${i+1}本目 失点<input type="number" class="score-against" value="0"></label>`).join("")}else $("scoreInputs").innerHTML='<label>前半 得点<input type="number" class="score-for" value="0"></label><label>前半 失点<input type="number" class="score-against" value="0"></label><label>後半 得点<input type="number" class="score-for" value="0"></label><label>後半 失点<input type="number" class="score-against" value="0"></label>'}
function slots(){const nums=String($("formationInput").value||"4-4-2").split(/[-‐‑‒–—―ー－]/).map(Number).filter(n=>n>0),roles=["DF","MF","FW","ST","L5"];const s=[{id:"GK1",label:"GK"}];nums.forEach((n,i)=>{for(let k=1;k<=n;k++)s.push({id:`${roles[i]||"L"}${k}`,label:`${roles[i]||"L"}${k}`})});return s}
function playerOptions(v){return'<option value="">未選択</option>'+masters.players.sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<option value="${p.id}" ${v===p.id?"selected":""}>#${esc(p.number)} ${esc(p.name)}</option>`).join("")}
function renderMemberEditor(){const root=$("memberEditorRoot"),trm=$("matchType").value==="trm";$("memberPanelTitle").textContent=trm?"TRMメンバー / フォーメーション":"スタメン表示 / フォーメーション";$("memberPanelNote").textContent=trm?"本数ごとにメンバー登録します。":"公式戦はスタメンと交代を登録できます。";if(!masters.players.length){root.innerHTML=empty("選手マスターがありません","設定で選手を追加してください");return}const sets=trm?Array.from({length:Number($("trmCount").value||3)},(_,i)=>[`set${i+1}`,`${i+1}本目メンバー`]):[["starter","スタメン設定"]];root.innerHTML=sets.map(([key,title])=>`<section class="member-set"><div><h4>${title}</h4><div class="member-rows">${slots().map(sl=>`<div class="member-row"><span class="pos-pill">${sl.label}</span><select data-member-set="${key}" data-member-slot="${sl.id}">${playerOptions(memberState[key]?.[sl.id]||"")}</select></div>`).join("")}</div></div><div class="mini-pitch">${miniPitch(key)}</div></section>`).join("")+(trm?"":subHtml());qsa("[data-member-slot]").forEach(sel=>sel.onchange=()=>{memberState[sel.dataset.memberSet]??={};memberState[sel.dataset.memberSet][sel.dataset.memberSlot]=sel.value;renderMemberEditor()});qsa("[data-sub-field]").forEach(i=>i.oninput=captureSubs);qsa("[data-sub-del]").forEach(b=>b.onclick=()=>{captureSubs();substitutions=substitutions.filter(s=>s.id!==b.dataset.subDel);renderMemberEditor()});const add=$("addSubBtn");if(add)add.onclick=()=>{captureSubs();substitutions.push({id:uid(),time:"",outPlayerId:"",inPlayerId:"",position:""});renderMemberEditor()}}
function miniPitch(key){return`<svg viewBox="0 0 500 320"><rect width="500" height="320" fill="#11813e"/><rect x="16" y="16" width="468" height="288" fill="none" stroke="#fff" stroke-width="3"/><line x1="250" y1="16" x2="250" y2="304" stroke="#fff" stroke-width="3"/>${slots().map((sl,i)=>{const pid=memberState[key]?.[sl.id],p=masters.players.find(x=>x.id===pid),x=60+(i%4)*120,y=70+Math.floor(i/4)*62;return`<g><circle cx="${x}" cy="${y}" r="20" fill="#fff"/><text x="${x}" y="${y+6}" text-anchor="middle" font-size="14" font-weight="800">${p?esc(p.number):sl.label}</text><text x="${x}" y="${y+36}" text-anchor="middle" font-size="11" fill="#fff">${p?esc(p.name):""}</text></g>`}).join("")}</svg>`}
function subHtml(){return`<section><h4>交代選手 / ポジション変更</h4><button id="addSubBtn" type="button">＋ 交代追加</button>${substitutions.map(s=>`<div class="sub-row" data-sub="${s.id}"><input data-sub-field="time" data-id="${s.id}" placeholder="55分" value="${esc(s.time)}"><select data-sub-field="outPlayerId" data-id="${s.id}">${playerOptions(s.outPlayerId)}</select><select data-sub-field="inPlayerId" data-id="${s.id}">${playerOptions(s.inPlayerId)}</select><input data-sub-field="position" data-id="${s.id}" placeholder="FW1" value="${esc(s.position)}"><button type="button" class="danger" data-sub-del="${s.id}">×</button></div>`).join("")}</section>`}
function captureMembers(){qsa("[data-member-slot]").forEach(sel=>{memberState[sel.dataset.memberSet]??={};memberState[sel.dataset.memberSet][sel.dataset.memberSlot]=sel.value})}
function captureSubs(){const map={};qsa("[data-sub-field]").forEach(i=>{map[i.dataset.id]??={id:i.dataset.id};map[i.dataset.id][i.dataset.subField]=i.value});substitutions=Object.values(map)}
function saveMatch(){captureMembers();captureSubs();const fors=qsa(".score-for").map(i=>Number(i.value||0)),ags=qsa(".score-against").map(i=>Number(i.value||0));const m={id:$("matchId").value||uid(),matchType:$("matchType").value,trmCount:Number($("trmCount").value||3),matchName:$("matchName").value||($("matchType").value==="trm"?"TRM":"公式戦"),category:$("matchCategory").value,opponentName:$("opponentName").value,matchDate:$("matchDate").value,formation:$("formationInput").value||"4-4-2",memberSets:clone(memberState),substitutions:clone(substitutions),scores:fors.map((v,i)=>({for:v,against:ags[i]||0})),totalFor:fors.reduce((a,b)=>a+b,0),totalAgainst:ags.reduce((a,b)=>a+b,0),videoUrl:$("videoUrl").value,matchMemo:$("matchMemo").value};const idx=matches.findIndex(x=>x.id===m.id);if(idx>=0)matches[idx]=m;else matches.unshift(m);saveMatches();clearMatch();renderMatches();toast("試合結果を保存しました")}
function editMatch(id){const m=matches.find(x=>x.id===id);if(!m)return;$("matchId").value=m.id;$("matchType").value=m.matchType||"official";$("trmCount").value=m.trmCount||3;$("matchName").value=m.matchName||"";$("matchCategory").value=m.category||"";$("opponentName").value=m.opponentName||"";$("matchDate").value=m.matchDate||today();$("formationInput").value=m.formation||"4-4-2";$("videoUrl").value=m.videoUrl||"";$("matchMemo").value=m.matchMemo||"";memberState=clone(m.memberSets||{});substitutions=clone(m.substitutions||[]);renderScoreInputs();qsa(".score-for").forEach((i,n)=>i.value=m.scores?.[n]?.for||0);qsa(".score-against").forEach((i,n)=>i.value=m.scores?.[n]?.against||0);renderMemberEditor();page("resultsPage")}
function clearMaterial(){["materialId","materialTitle","materialMemo"].forEach(id=>$(id).value="");$("materialDate").value=today();pendingMaterialFile=null;$("materialFileInput").value=""}
function handleFile(file){if(!file)return;if(file.size>12*1024*1024){alert("12MB以下のファイルにしてください");return}const r=new FileReader();r.onload=()=>{pendingMaterialFile={name:file.name,type:file.type,size:file.size,data:r.result};toast("ファイルを読み込みました")};r.readAsDataURL(file)}
function saveMaterial(){const id=$("materialId").value||uid();let old=materials.find(m=>m.id===id);const m={id,title:$("materialTitle").value||"無題の資料",category:$("materialCategory").value,date:$("materialDate").value||today(),memo:$("materialMemo").value,file:pendingMaterialFile||old?.file||null,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const i=materials.findIndex(x=>x.id===id);if(i>=0)materials[i]=m;else materials.unshift(m);saveMaterials();clearMaterial();renderMaterials();toast("資料を保存しました")}
function renderMaterials(){const list=$("materialList");list.innerHTML=materials.map(m=>`<article class="card"><h3>${esc(m.title)}</h3><div class="badges"><span class="badge">${esc(m.category)}</span><span class="badge">${esc(m.date)}</span></div><p>${esc(m.memo||"")}</p>${m.file?`<a href="${m.file.data}" download="${esc(m.file.name)}">ファイルを開く / 保存</a>`:""}<div class="card-actions"><button data-material-edit="${m.id}">編集</button><button class="danger" data-material-del="${m.id}">削除</button></div></article>`).join("")||empty("資料がありません","PDFやPowerPointを保存できます");qsa("[data-material-edit]").forEach(b=>b.onclick=()=>editMaterial(b.dataset.materialEdit));qsa("[data-material-del]").forEach(b=>b.onclick=()=>{if(confirm("削除しますか？")){materials=materials.filter(m=>m.id!==b.dataset.materialDel);saveMaterials();renderMaterials()}})}
function editMaterial(id){const m=materials.find(x=>x.id===id);if(!m)return;$("materialId").value=m.id;$("materialTitle").value=m.title;$("materialCategory").value=m.category;$("materialDate").value=m.date;$("materialMemo").value=m.memo||"";pendingMaterialFile=m.file||null;page("materialsPage")}
function readMasters(){masters.categories=$("masterCategories").value.split(/\n|,/).map(s=>s.trim()).filter(Boolean);masters.ages=$("masterAges").value.split(/\n|,/).map(s=>s.trim()).filter(Boolean);masters.times=$("masterTimes").value.split(/\n|,/).map(s=>s.trim()).filter(Boolean);masters.tags=$("masterTags").value.split(/\n|,/).map(s=>s.trim()).filter(Boolean);masters.surfaceType=$("surfaceType").value;saveMasters();refreshSelects();renderAll();toast("マスター保存")}
function renderPlayers(){$("playerMasterList").innerHTML=masters.players.map(p=>`<span class="player-item">#${esc(p.number)} ${esc(p.name)} <button class="danger" data-player-del="${p.id}">×</button></span>`).join("")||"<p>選手が未登録です。</p>";qsa("[data-player-del]").forEach(b=>b.onclick=()=>{masters.players=masters.players.filter(p=>p.id!==b.dataset.playerDel);saveMasters();renderPlayers();renderMemberEditor()})}
function addPlayer(){const num=$("playerNumberInput").value.trim(),name=$("playerNameInput").value.trim();if(!num||!name){toast("背番号と名前を入力");return}masters.players.push({id:uid(),number:num,name});$("playerNumberInput").value="";$("playerNameInput").value="";saveMasters();renderPlayers();renderMemberEditor()}
function downloadJson(){const data={version:"v28-from-v23",sessions,masters,matches,materials};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="teamboard-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importJson(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);sessions=data.sessions||sessions;masters={...defaultMasters,...(data.masters||masters)};matches=data.matches||matches;materials=data.materials||materials;saveAll();saveMasters();saveMatches();saveMaterials();refreshSelects();renderAll();toast("読み込みました")}catch(e){alert("読み込みに失敗しました")}};r.readAsText(file)}
function renderAll(){refreshSelects();renderRecent();renderSearch();renderMatches();renderMaterials();renderPlayers();$("syncStatus").textContent=`指導案 ${sessions.length}件 / 試合 ${matches.length}件 / 資料 ${materials.length}件`}
function init(){ensureData();sessions=sessions.map(normalizeSession);draft=newEmptySession();refreshSelects();fillSessionForm();renderAll();renderScoreInputs();renderMemberEditor();qsa(".nav-btn").forEach(b=>b.onclick=()=>page(b.dataset.page));qsa("[data-page-jump]").forEach(b=>b.onclick=()=>page(b.dataset.pageJump));$("brandHomeBtn").onclick=() => page("homePage");$("settingsOpenBtn").onclick=()=>page("settingsPage");$("syncOpenBtn").onclick=()=>page("syncPage");$("homeCreateBtn").onclick=newSession;$("newFromTopBtn").onclick=newSession;$("homeSearchBtn").onclick=()=>page("searchPage");$("homeResultsBtn").onclick=()=>page("resultsPage");$("homeMaterialsBtn").onclick=()=>page("materialsPage");$("newBlankBtn").onclick=newSession;$("saveBtn").onclick=saveDraft;qsa(".part").forEach(b=>b.onclick=()=>setPart(b.dataset.part));qsa(".tool").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$("board").addEventListener("pointerdown",boardDown);$("board").addEventListener("pointermove",boardMove);$("board").addEventListener("pointerup",boardUp);$("board").addEventListener("pointercancel",boardUp);$("sizeDownBtn").onclick=()=>adjustSize(.9);$("sizeUpBtn").onclick=()=>adjustSize(1.1);$("duplicateBtn").onclick=duplicate;$("deleteSelectedBtn").onclick=del;$("applyColorBtn").onclick=applyColor;$("rotateLeftBtn").onclick=()=>rotate(-45);$("rotateRightBtn").onclick=()=>rotate(45);$("undoBtn").onclick=()=>{currentObjects().pop();selectedObjectId="";renderBoard()};$("clearBtn").onclick=()=>{if(confirm("クリアしますか？")){draft.parts[activePart].objects=[];renderBoard()}};["keyword","partFilter","categoryFilter","tagFilter"].forEach(id=>{$(id).oninput=renderSearch;$(id).onchange=renderSearch});$("clearSearchBtn").onclick=()=>{["keyword","partFilter","categoryFilter","tagFilter"].forEach(id=>$(id).value="");renderSearch()};$("newMatchBtn").onclick=clearMatch;$("matchType").onchange=()=>{renderScoreInputs();renderMemberEditor()};$("trmCount").onchange=()=>{renderScoreInputs();renderMemberEditor()};$("formationInput").oninput=renderMemberEditor;$("saveMatchBtn").onclick=saveMatch;$("clearMaterialFormBtn").onclick=clearMaterial;$("materialFileInput").onchange=e=>handleFile(e.target.files[0]);$("saveMaterialBtn").onclick=saveMaterial;$("saveMastersBtn").onclick=readMasters;$("addPlayerBtn").onclick=addPlayer;$("playerNumberInput").onkeydown=e=>{if(e.key==="Enter")addPlayer()};$("playerNameInput").onkeydown=e=>{if(e.key==="Enter")addPlayer()};$("downloadBtn").onclick=downloadJson;$("importJsonInput").onchange=e=>importJson(e.target.files[0]);setTool("attack");renderBoard()}
document.addEventListener("DOMContentLoaded",init);
})();